#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Golang
export GOPATH=$HOME/dev/go
export G015VENDOREXPERIMENT=1

# Pyenv
export PYENV_ROOT=$HOME/.pyenv

# JAVA
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

# Android
export ANDROID_HOME=$HOME/Library/Android/sdk

# Key bind
bindkey -M viins 'jj' vi-cmd-mode

export TERM=xterm-256color

# tabtab source for yarn package
# uninstall by removing these lines or running `tabtab uninstall yarn`
[[ -f /usr/local/lib/node_modules/yarn-completions/node_modules/tabtab/.completions/yarn.zsh ]] && . /usr/local/lib/node_modules/yarn-completions/node_modules/tabtab/.completions/yarn.zsh