#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Golang
export GOPATH=$HOME/projects/go
export G015VENDOREXPERIMENT=1

# Pyenv
export PYENV_ROOT=$HOME/.pyenv

alias qlot="~/.roswell/bin/qlot"

# Key bind
bindkey -M viins 'jj' vi-cmd-mode

export TERM=xterm-256color
